###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2022. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: Content
metadata:
  name: content
  labels:
    app.kubernetes.io/instance: ibm-dba-content
    app.kubernetes.io/managed-by: ibm-dba-content
    app.kubernetes.io/name: ibm-dba-content
    release: 23.0.1
spec:
  appVersion: 23.0.1

  ## MUST exist, used to accept ibm license, valid value only can be "accept" 
  license:
    accept: true
  ## The deployment type as selected by the user.  Possible values are: Starter and Production.
  content_deployment_type: Starter

  ## The optional components to be installed if listed here.
  ## The optional components are: Content Manager Image Services (cmis), css (Content Search Services), es (External Share), tm (Task Manager),
  ##                              IBM Enterprise Records (ier) and IBM Content Collector for SAP (iccsap)
  ## NOTE: ier, and iccsap does NOT support integration with ums.
  ## NOTE: es does not work when using Zen and IAM for authentication.
  content_optional_components:
    bai: false
    cmis: false
    css: false
    iccsap: false
    ier: false
    tm: false
  ## TIPS: The names of all variables in the spec field are converted to snake_case by the operator before running ansible
  ## For example, serviceAccount in the spec becomes service_account in ansible.
  ## It is recommended that you perform some type validation in Ansible on the variables to ensure that
  ## your application is receiving expected input.
  ## shared configuration among all tribe
  shared_configuration:
    ## FileNet Content Manager (FNCM) license and possible values are: user, non-production, and production.
    ## This value could be different from the rest of the licenses.
    sc_deployment_fncm_license: non-production

    ## Specify the RunAsUser for the security context of the pod.  This is usually a numeric value that corresponds to a user ID
    sc_run_as_user: 

    ## This is the deployment platform supported for CP4A and the possible values are: ROKS, OCP, and other (which includes all Certified Kubernetes platforms)
    sc_deployment_platform: "OCP"

    ## This is the deployment hostname suffix, this is optional and the default hostname suffix will be used as {meta.namespace}.router-canonicalhostname
    # sc_deployment_hostname_suffix:
    
    ## This is necessary if you want to use your own JDBC drivers and/or need to provide ICCSAP drivers.  If you are providing multiple JDBC drivers and ICCSAP drivers, 
    ## all the files must be compressed in a single file.
    ## First you need to package your drivers into a compressed package in the format of "saplibs/drivers_files" and/or 
    ## "jdbc/db2|oracle|postgresql|sqlserver/driver_files". For example, if you are provding your own DB2 and Oracle JDBC drivers and ICCSAP drivers, then the compressed 
    ## file should have the following structure and content:
    ##   /jdbc/db2/db2jcc4.jar
    ##   /jdbc/db2/db2jcc_license_cu.jar
    ##   /jdbc/oracle/ojdbc8.jar
    ##   /saplibs/libicudata.so.50
    ##   /saplibs/...
    ## Then you need to put the compressed package on an anonymously accesible web server and provide the link here.
    ## This CR can handle .zip files using unzip as well as .tar, .tar.gz, .tar.bz2, .tar.xz. Does not handle .gz files, .bz2 files, .xz, or .zst files that do not contain a .tar archive.
    sc_drivers_url:

    storage_configuration:
      sc_dynamic_storage_classname: "ocs-storagecluster-cephfs"
      sc_block_storage_classname: "ocs-storagecluster-cephfs"
  ########################################################################
  ########      IBM FileNet Content Manager configuration         ########
  ########################################################################
  ecm_configuration:
    cpe:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/cpe
        tag: "23.0.1"
    css:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/css
        tag: "23.0.1"
    graphql:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/graphql
        tag: "23.0.1"
    cmis:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/cmis
        tag: "23.0.1"
    tm:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/taskmgr
        tag: "23.0.1"
  ########################################################################
  ########   IBM Business Automation Navigator configuration      ########
  ########################################################################
  navigator_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/ban/navigator
      tag: "23.0.1"
     
  ########################################################################
  ########   IBM Enterprise Records configuration      ########
  ########################################################################     
  ier_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/ier/ier
      tag: "23.0.1"

 ########################################################################
 ########             IBM Content Collector for SAP              ########
 ########################################################################
  iccsap_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/iccsap/iccsap
      tag: "23.0.1"
