kind: Secret
apiVersion: v1
metadata:
  name: ldap-bind-secret
  namespace: cp4ba
stringData:
  ldapPassword: Passw0rd
  ldapUsername: cn=admin,dc=cp
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: ibm-ier-secret
  namespace: cp4ba
stringData:
  keystorePassword: Passw0rd
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: ibm-fncm-secret
  namespace: cp4ba
stringData:
  appLoginPassword: Passw0rd
  appLoginUsername: cpadmin
  gcdDBPassword: <set-by-script>
  gcdDBUsername: db2inst1
  keystorePassword: Passw0rd
  ltpaPassword: Passw0rd
  os1DBPassword: <set-by-script>
  os1DBUsername: db2inst1
  os2DBPassword: <set-by-script>
  os2DBUsername: db2inst1
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: ibm-ban-secret
  namespace: cp4ba
stringData:
  appLoginPassword: Passw0rd
  appLoginUsername: cpadmin
  jMailPassword: Passw0rd
  jMailUsername: cpadmin@cp.local
  keystorePassword: Passw0rd
  ltpaPassword: Passw0rd
  navigatorDBPassword: <set-by-script>
  navigatorDBUsername: db2inst1
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: ibm-dba-ums-secret
  namespace: cp4ba
stringData:
  adminPassword: Passw0rd
  adminUser: cpadmin
  oauthDBPassword: <set-by-script>
  oauthDBUser: db2inst1
  tsDBPassword: <set-by-script>
  tsDBUser: db2inst1
type: Opaque
