#!/bin/sh

# Create all our database sequentially

function create_dbs {
    echo "Starting OS1DB creation"
    db2 -v "CREATE DATABASE OS1DB AUTOMATIC STORAGE YES PAGESIZE 32 K"

    echo "Starting OS2DB creation"
    db2 -v "CREATE DATABASE OS2DB AUTOMATIC STORAGE YES PAGESIZE 32 K"

    echo "Starting UMS creation"
    db2 -v "CREATE DATABASE UMS AUTOMATIC STORAGE YES PAGESIZE 32 K"

    echo "Starting GCDDB creation"
    db2 -v "CREATE DATABASE GCDDB AUTOMATIC STORAGE YES PAGESIZE 32 K"

    echo "Starting NAVDB creation"
    db2 -v "CREATE DATABASE NAVDB AUTOMATIC STORAGE YES PAGESIZE 32 K"
}

function setup_osdb {
    dbname=$1
    echo "starting $dbname setup"

    db2 -v connect to $dbname
    db2 -v DROP TABLESPACE USERSPACE1
    db2 -v UPDATE DATABASE CONFIGURATION FOR $dbname USING APPLHEAPSZ 2560
    db2 -v UPDATE DATABASE CONFIGURATION FOR $dbname USING CUR_COMMIT ON DEFERRED
    db2 -v CREATE LARGE TABLESPACE "DATA_TS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE USING STOGROUP IBMSTOGROUP AUTORESIZE YES BUFFERPOOL IBMDEFAULTBP OVERHEAD INHERIT TRANSFERRATE INHERIT DROPPED TABLE RECOVERY ON DATA TAG INHERIT
    db2 -v CREATE LARGE TABLESPACE "INDEX_TS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE USING STOGROUP IBMSTOGROUP AUTORESIZE YES BUFFERPOOL IBMDEFAULTBP OVERHEAD INHERIT TRANSFERRATE INHERIT DROPPED TABLE RECOVERY ON DATA TAG INHERIT
    db2 -v CREATE LARGE TABLESPACE "LOB_TS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE USING STOGROUP IBMSTOGROUP AUTORESIZE YES BUFFERPOOL IBMDEFAULTBP OVERHEAD INHERIT TRANSFERRATE INHERIT DROPPED TABLE RECOVERY ON DATA TAG INHERIT
    db2 -v CREATE USER TEMPORARY TABLESPACE "TEMP_TS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE USING STOGROUP IBMSTOGROUP BUFFERPOOL IBMDEFAULTBP OVERHEAD INHERIT TRANSFERRATE INHERIT DROPPED TABLE RECOVERY OFF
    db2 -v CREATE LARGE TABLESPACE "VWDATA_TS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE USING STOGROUP IBMSTOGROUP AUTORESIZE YES BUFFERPOOL IBMDEFAULTBP OVERHEAD INHERIT TRANSFERRATE INHERIT DROPPED TABLE RECOVERY ON DATA TAG INHERIT
    db2 -v connect reset

    echo "setup for $dbname complete"
}


function delete_dbs {
     echo "Dropping all FileNet db2 dbs"
     db2 -v "DROP DATABASE OS1DB"
     db2 -v "DROP DATABASE OS2DB"
     db2 -v "DROP DATABASE UMS"
     db2 -v "DROP DATABASE GCDDB"
     db2 -v "DROP DATABASE NAVDB"
}


function main {
    echo "starting DB2 setup for Filenet object stores" && date
    create_dbs
    setup_osdb "OS1DB"
    setup_osdb "OS2DB"
}

main > /tmp/filenet-db2-setup.log
#delete_dbs
echo "FILENETDB2SETUPFINISHED"
echo "complete"
