apiVersion: icp4a.ibm.com/v1
kind: Content
metadata:
  name: "icp4adeploy"
  labels:
    app.kubernetes.io/instance: ibm-dba-content
    app.kubernetes.io/managed-by: ibm-dba-content
    app.kubernetes.io/name: ibm-dba-content
    release: "22.0.1"
spec:
  content_optional_components:
    bai: false      # Business Automation Insights
    cmis: false     # Content Manager Development
    css: false      # Content Search Services
    es: false       # External Share
    iccsap: false   # ICC SAP (connector)
    ier: false      # IBM Enterprise Records
    tm: false       # Task Manager
  license:
    accept: true
  appVersion: 22.0.1
  ibm_license: accept
  shared_configuration:
    no_log: false
    sc_deployment_fncm_license: non-production
    sc_deployment_baw_license: non-production
    sc_deployment_license: non-production
    show_sensitive_log: true
    sc_deployment_patterns: ""
    sc_optional_components: ""
    sc_deployment_type: production
    sc_deployment_profile_size: small
    sc_deployment_platform: "ROKS"
    sc_ingress_enable: false
    sc_image_repository: cp.icr.io
    trusted_certificate_list: []
    storage_configuration:
      sc_slow_file_storage_classname: "ocs-storagecluster-cephfs"
      sc_medium_file_storage_classname: "ocs-storagecluster-cephfs"
      sc_fast_file_storage_classname: "ocs-storagecluster-cephfs"
      sc_block_storage_classname: "ocs-storagecluster-cephfs"
  ldap_configuration:
    lc_selected_ldap_type: IBM Security Directory Server
    lc_ldap_server: "openldap-openldap-stack-ha.openldap.svc.cluster.local"
    lc_ldap_port: "389"
    lc_bind_secret: ldap-bind-secret
    lc_ldap_base_dn: dc=cp
    lc_ldap_ssl_enabled: false
    lc_ldap_user_name_attribute: "*:cn"
    lc_ldap_user_display_name_attr: cn
    lc_ldap_group_base_dn: ou=Groups,dc=cp
    lc_ldap_group_name_attribute: "*:cn"
    lc_ldap_group_display_name_attr: cn
    lc_ldap_group_membership_search_filter: "(|(&(objectclass=groupofnames)(member={0}))(&(objectclass=groupofuniquenames)(uniquemember={0})))"
    lc_ldap_group_member_id_map: "groupofnames:member"
    tds:
      lc_user_filter: "(&(cn=%v)(objectclass=inetOrgPerson))"
      lc_group_filter: "(&(cn=%v)(|(objectclass=groupofnames)(objectclass=groupofuniquenames)(objectclass=groupofurls)))"
  datasource_configuration:
    dc_ssl_enabled: false
    dc_icn_datasource:
      dc_database_type: db2
      dc_common_icn_datasource_name: ECMClientDS
      database_servername: "c-test-db2u-internal.db2.svc"
      database_port: "50052"
      database_name: NAVDB
    dc_gcd_datasource:
      dc_database_type: db2
      dc_common_gcd_datasource_name: FNGCDDS
      dc_common_gcd_xa_datasource_name: FNGCDDSXA
      database_servername: "c-test-db2u-internal.db2.svc"
      database_name: GCDDB
      database_port: "50052"
    dc_os_datasources:
      - dc_database_type: db2
        dc_os_label: os1
        dc_common_os_datasource_name: OS1
        dc_common_os_xa_datasource_name: OS1XA
        database_servername: "c-test-db2u-internal.db2.svc"
        database_name: OS1DB
        database_port: "50052"
  navigator_configuration:
    ban_secret_name: ibm-ban-secret
    replica_count: 1
    icn_production_setting:
      jvm_customize_options: ""
      icn_table_space: ICNDB_TS
      copy_files_to_war: navigator_war_filesources.xml
    auto_scaling:
      enabled: false
  ecm_configuration:
    show_sensitive_log: true
    fncm_secret_name: ibm-fncm-secret
    cpe:
      replica_count: 1
      cpe_production_setting:
        gcd_jndi_name: FNGCDDS
        gcd_jndixa_name: FNGCDDSXA
        license_model: FNCM.PVUNonProd
    graphql:
      replica_count: 1
      graphql_production_setting:
        license_model: FNCM.PVUNonProd
        enable_graph_iql: true
    tm:
      replica_count: 1
      tm_production_setting:
        security_roles_to_group_mapping:
          task_admins:
            groups: [cpadmins]
          task_users:
            groups: [cpusers]
          task_auditors:
            groups: [cpadmins]
    cmis:
      replica_count: 1
    css:
      replica_count: 1
  initialize_configuration:
    ic_domain_creation:
      domain_name: P8DOMAIN
      encryption_key: 128
    ic_ldap_creation:
      ic_ldap_admin_user_name:
        - cpadmin
      ic_ldap_admins_groups_name:
        - cpadmins
      ic_ldap_name: ldap
    ic_css_creation:
      - css_text_search_server_name: "icp4adeploy-css-1"
    ic_css_index_area:
      - object_store_name: OS1
        index_area_name: os1_index_area
    ic_enable_cbr:
      - object_store_name: OS1
    ic_obj_store_creation:
      object_stores:
        - oc_cpe_obj_store_display_name: OS1
          oc_cpe_obj_store_symb_name: OS1
          oc_cpe_obj_store_conn:
            name: OS1_dbconnection
            dc_os_datasource_name: OS1
            dc_os_xa_datasource_name: OS1XA
          oc_cpe_obj_store_admin_user_groups:
            - cpadmin
            - cpadmins
          oc_cpe_obj_store_asa_name: os1_asa
          oc_cpe_obj_store_asa_file_systems_storage_device_name: os1_file_system_storage
          oc_cpe_obj_store_asa_root_dir_path: /opt/ibm/asa/os1_storagearea1
          oc_cpe_obj_store_addons_list:
            - "{CE460ADD-0000-0000-0000-000000000004}" # 5.2.1 Base Application Extensions (default)
            - "{CE460ADD-0000-0000-0000-000000000001}" # 5.2.1 Base Content Engine Extensions (default)
            - "{CE460ADD-0000-0000-0000-000000000003}" # (default)
            - "{CE460ADD-0000-0000-0000-000000000005}" # (default)
            - "{CE511ADD-0000-0000-0000-000000000006}" # (default)
            - "{CE460ADD-0000-0000-0000-000000000008}" # (default)
            - "{CE460ADD-0000-0000-0000-000000000007}" # (default)
            - "{CE460ADD-0000-0000-0000-000000000009}" # (default)
            - "{CE460ADD-0000-0000-0000-00000000000A}" # (default)
            - "{CE460ADD-0000-0000-0000-00000000000B}" # (default)
            - "{CE460ADD-0000-0000-0000-00000000000D}" # (default)
            - "{CE511ADD-0000-0000-0000-00000000000F}" # (default)
            - "{CE511ADD-0000-0000-0000-000000000010}" # 5.2.1 Teamspace Extensions
            - "{CE511ADD-0000-0000-0000-000000000015}" # 5.2.1 Custom Role Extensions
            - "{CE521ADD-0000-0000-0000-000000000016}" # 5.2.1 Social Collaboration Role Extensions
            - "{CE552ADD-0000-0000-0000-00000000001C}" # 5.5.2 Core Collaboration Extensions
            - "{CE551ADD-0000-0000-0000-000000000011}" # 5.5.1 Social Collaboration Base Extensions
    ic_icn_init_info:
      icn_repos:
        - add_repo_id: OS1
          add_repo_os_sym_name: OS1
          add_repo_os_dis_name: OS1
      icn_desktop:
        - add_desktop_id: OS1
          add_desktop_name: OS1
          add_desktop_description: OS1
          add_desktop_repo_id: OS1
  verify_configuration:
    vc_icn_verification:
      - vc_icn_repository: OS1
        vc_icn_desktop_id: OS1
    vc_cpe_verification:
      vc_cpe_cbr:
        - cbr_cpe_obj_store_name: OS1
