kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "openldap-anyuid"
  namespace: openldap
subjects:
  - kind: ServiceAccount
    name: default
    namespace: openldap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:openshift:scc:anyuid"
---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-ltb-passwd
  namespace: openldap
  labels:
    app: openldap-stack-ha
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: "Passw0rd"
---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-openldap-stack-ha
  namespace: openldap
  labels:
    app: openldap-stack-ha
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: "Passw0rd"
  LDAP_CONFIG_PASSWORD: "Passw0rd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-phpldapadmin
  namespace: openldap
  labels:
    app: phpldapadmin
data:
  PHPLDAPADMIN_HTTPS: "false"
  PHPLDAPADMIN_LDAP_HOSTS: openldap-openldap-stack-ha.openldap.svc.cluster.local
  PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-openldap-stack-ha-customldif
  namespace: openldap
  labels:
    app: openldap-stack-ha
data:
  01-sds-schema.ldif: |-
    dn: cn=sds,cn=schema,cn=config
    objectClass: olcSchemaConfig
    cn: sds
    olcAttributeTypes: {0}( 1.3.6.1.4.1.42.2.27.4.1.6 NAME 'ibm-entryUuid' DESC 
      'Uniquely identifies a directory entry throughout its life.' EQUALITY caseIgnoreMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE )
    olcObjectClasses: {0}( 1.3.6.1.4.1.42.2.27.4.2.1 NAME 'sds' DESC 'sds' SUP top AUXILIARY MUST ( cn $ ibm-entryuuid ) )
  02-default-users.ldif: |-
    # Units
    dn: ou=Users,dc=cp
    objectClass: organizationalUnit
    ou: Users

    dn: ou=Groups,dc=cp
    objectClass: organizationalUnit
    ou: Groups

    # Users
    dn: uid=cpadmin,ou=Users,dc=cp
    objectClass: inetOrgPerson
    objectClass: sds
    cn: cpadmin
    sn: cpadmin
    uid: cpadmin
    mail: cpadmin@cp.local
    userpassword:: UGFzc3cwcmQ=
    employeeType: admin
    ibm-entryuuid: e6c41859-ced3-4772-bfa3-6ebbc58ec78a

    dn: uid=cpadmin1,ou=Users,dc=cp
    objectClass: inetOrgPerson
    objectClass: sds
    cn: cpadmin1
    sn: cpadmin1
    uid: cpadmin1
    mail: cpadmin1@cp.local
    userpassword:: UGFzc3cwcmQ=
    employeeType: admin
    ibm-entryuuid: 40324128-84c8-48c3-803d-4bef500f84f1

    dn: uid=cpadmin2,ou=Users,dc=cp
    objectClass: inetOrgPerson
    objectClass: sds
    cn: cpadmin2
    sn: cpadmin2
    uid: cpadmin2
    mail: cpadmin2@cp.local
    userpassword:: UGFzc3cwcmQ=
    employeeType: admin
    ibm-entryuuid: 53f96449-2b7e-4402-a58a-9790c5089dd0

    dn: uid=cpuser,ou=Users,dc=cp
    objectClass: inetOrgPerson
    objectClass: sds
    cn: cpuser
    sn: cpuser
    uid: cpuser
    mail: cpuser@cp.local
    userpassword:: UGFzc3cwcmQ=
    ibm-entryuuid: 30183bb0-1012-4d23-8ae2-f94816b91a75

    dn: uid=cpuser1,ou=Users,dc=cp
    objectClass: inetOrgPerson
    objectClass: sds
    cn: cpuser1
    sn: cpuser1
    uid: cpuser1
    mail: cpuser1@cp.local
    userpassword:: UGFzc3cwcmQ=
    ibm-entryuuid: ced63be9-411a-4222-b97e-189ddec2beab

    dn: uid=cpuser2,ou=Users,dc=cp
    objectClass: inetOrgPerson
    objectClass: sds
    cn: cpuser2
    sn: cpuser2
    uid: cpuser2
    mail: cpuser2@cp.local
    userpassword:: UGFzc3cwcmQ=
    ibm-entryuuid: a208fc01-96aa-43f6-9279-35e9725d9fbd

    # Groups
    dn: cn=cpadmins,ou=Groups,dc=cp
    objectClass: groupOfNames
    objectClass: sds
    cn: cpadmins
    ibm-entryuuid: 4196cb9e-1ed7-4c02-bb0d-792cb7bfa768
    member: uid=cpadmin,ou=Users,dc=cp
    member: uid=cpadmin1,ou=Users,dc=cp
    member: uid=cpadmin2,ou=Users,dc=cp

    dn: cn=cpusers,ou=Groups,dc=cp
    objectClass: groupOfNames
    objectClass: sds
    cn: cpusers
    ibm-entryuuid: fc4ded27-8c6a-4a8c-ad9e-7be65369758c
    member: uid=cpadmin,ou=Users,dc=cp
    member: uid=cpadmin1,ou=Users,dc=cp
    member: uid=cpadmin2,ou=Users,dc=cp
    member: uid=cpuser,ou=Users,dc=cp
    member: uid=cpuser1,ou=Users,dc=cp
    member: uid=cpuser2,ou=Users,dc=cp

    dn: cn=cpusers1,ou=Groups,dc=cp
    objectClass: groupOfNames
    objectClass: sds
    cn: cpusers1
    ibm-entryuuid: 7249b636-39b4-456b-8e52-ea4340ee4a6c
    member: uid=cpuser,ou=Users,dc=cp
    member: uid=cpuser1,ou=Users,dc=cp
    member: uid=cpuser2,ou=Users,dc=cp

    # FNCM Task Manager groups
    dn: cn=TaskAdmins,ou=Groups,dc=cp
    objectClass: groupOfNames
    objectClass: sds
    cn: TaskAdmins
    ibm-entryuuid: 001f19c1-cfcc-4b35-b080-85e946eed707
    member: uid=cpadmin,ou=Users,dc=cp

    dn: cn=TaskUsers,ou=Groups,dc=cp
    objectClass: groupOfNames
    objectClass: sds
    cn: TaskUsers
    ibm-entryuuid: 7b370bce-da87-4135-828d-f80b5ca9b80b
    member: uid=cpadmin,ou=Users,dc=cp
    member: uid=cpuser,ou=Users,dc=cp

    dn: cn=TaskAuditors,ou=Groups,dc=cp
    objectClass: groupOfNames
    objectClass: sds
    cn: TaskAuditors
    ibm-entryuuid: 1b85d3b3-bba7-4f4c-a3b1-255cdf9885c0
    member: uid=cpadmin,ou=Users,dc=cp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-openldap-stack-ha-env
  namespace: openldap
  labels:
    app: openldap-stack-ha
data:
  CONTAINER_LOG_LEVEL: "4"
  KEEP_EXISTING_CONFIG: "false"
  LDAP_BACKEND: mdb
  LDAP_DOMAIN: cp
  LDAP_LOG_LEVEL: "256"
  LDAP_ORGANISATION: CP
  LDAP_READONLY_USER: "false"
  LDAP_READONLY_USER_PASSWORD: readonly
  LDAP_READONLY_USER_USERNAME: readonly
  LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
  LDAP_RFC2307BIS_SCHEMA: "false"
  LDAP_SSL_HELPER_PREFIX: ldap
  LDAP_TLS: "true"
  LDAP_TLS_CA_CRT_FILENAME: ca.crt
  LDAP_TLS_CIPHER_SUITE: NORMAL
  LDAP_TLS_CRT_FILENAME: tls.crt
  LDAP_TLS_DH_PARAM_FILENAME: dhparam.pem
  LDAP_TLS_ENFORCE: "false"
  LDAP_TLS_KEY_FILENAME: tls.key
  LDAP_TLS_PROTOCOL_MIN: "3.0"
  LDAP_TLS_REQCERT: never
  LDAP_TLS_VERIFY_CLIENT: never
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-phpldapadmin
  namespace: openldap
  labels:
    app: phpldapadmin
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: phpldapadmin
    release: openldap
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-openldap-stack-ha
  namespace: openldap
  labels:
    app: openldap-openldap-stack-ha
spec:
  type: ClusterIP
  ports:
    - name: ldap-port
      protocol: TCP
      port: 389
      targetPort: ldap-port
    - name: ssl-ldap-port
      protocol: TCP
      port: 636
      targetPort: ssl-ldap-port
  sessionAffinity: None
  selector:
    app: openldap-openldap-stack-ha
    release: openldap
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-openldap-stack-ha-headless
  namespace: openldap
  labels:
    app: openldap-openldap-stack-ha
spec:
  ports:
    - port: 389
      name: ldap-port
      targetPort: ldap-port
  clusterIP: None
  selector:
    app: openldap-openldap-stack-ha
    release: openldap
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: openldap-phpldapadmin
  namespace: openldap
  labels:
    app: phpldapadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
      release: openldap
  template:
    metadata:
      labels:
        app: phpldapadmin
        release: openldap
    spec:
      containers:
        - name: phpldapadmin
          image: "osixia/phpldapadmin:0.9.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: openldap-phpldapadmin
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap-openldap-stack-ha
  namespace: openldap
  labels:
    app: openldap-openldap-stack-ha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap-openldap-stack-ha
      release: openldap
  serviceName: openldap-openldap-stack-ha-headless
  template:
    metadata:
      annotations:
        checksum/configmap-env: c47d8391c4f489a594096a2041c1a23677f2f76783b8294c2c291a44f74eaaef
        checksum/configmap-customldif: 8518bf3def0bc970665ed6fc52929a5b497e79e3e15937c7eac1b4f0e952b80b
      labels:
        app: openldap-openldap-stack-ha
        release: openldap
    spec:
      initContainers:
      containers:
        - name: openldap-stack-ha
          image: "osixia/openldap:1.5.0"
          imagePullPolicy: Always
          args:
            - -l
            - info
            - --copy-service
          ports:
            - name: ldap-port
              containerPort: 389
            - name: ssl-ldap-port
              containerPort: 636
          envFrom:
            - configMapRef:
                name: openldap-openldap-stack-ha-env
            - secretRef:
                name: openldap-openldap-stack-ha
          volumeMounts:
            - name: data
              mountPath: /var/lib/ldap
              subPath: data
            - name: data
              mountPath: /etc/ldap/slapd.d
              subPath: config-data
            - name: data
              mountPath: /container/service/slapd/assets/certs
            - name: custom-ldif-files
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          livenessProbe:
            tcpSocket:
              port: ldap-port
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: ldap-port
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: openldap-openldap-stack-ha
                  release: openldap
      volumes:
        - name: custom-ldif-files
          configMap:
            name: openldap-openldap-stack-ha-customldif
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
      spec:
        accessModes:
          - "ReadWriteMany"
        resources:
          requests:
            storage: "8Gi"
        storageClassName: "ocs-storagecluster-cephfs"
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: openldap-phpldapadmin
  namespace: openldap
  labels:
    app: phpldapadmin
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: openldap-phpldapadmin
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
